#!/dis/sh

load expr

name=$%
current=`{basename $name}
currentx=`{grep -n '^'$current'([      ]|$)' index | sed 's/:.*//'}

pagex=${expr $currentx 1 +}
page=`{sed -n $pagex^p index}
if{~ $#page 0}{
       echo no such page
       exit 0
}

Slide $page
