9c  asm-386.S
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp os.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/win-x11a.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp emu.root.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/lock.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devroot.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devcons.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devenv.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devmnt.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devpipe.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devprog.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devprof.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devsrv.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devdup.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devssl.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devcap.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp devfs.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devcmd.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devtab.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp cmd.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devindir.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devdraw.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devpointer.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devsnarf.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devwmsz.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devip.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/ipif6-posix.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/ipaux.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp deveia.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devaudio.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp audio-oss.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/devmem.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/srv.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/alloc.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/cache.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/chan.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/dev.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/dial.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/dis.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/discall.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/env.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/error.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/errstr.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/exception.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/exportfs.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/inferno.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/latin1.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/kproc-pthreads.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/main.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/parse.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/pgrp.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/print.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/proc.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/qio.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/random.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. segflush-386.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/sysfile.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp -I. ../port/uqid.c
9c '-DROOT="."' -DEMU -I. -I../port -I../../Linux/386/include -I../../include -I../../libinterp '-DKERNDATE='1353522581 emu.c
9l  -o o.emu asm-386.o os.o win-x11a.o emu.root.o lock.o devroot.o devcons.o devenv.o devmnt.o devpipe.o devprog.o devprof.o devsrv.o devdup.o devssl.o devcap.o devfs.o devcmd.o cmd.o devtab.o devindir.o devdraw.o devpointer.o devsnarf.o devwmsz.o devip.o ipif6-posix.o ipaux.o deveia.o devaudio.o audio-oss.o devmem.o srv.o alloc.o cache.o chan.o dev.o dial.o dis.o discall.o env.o error.o errstr.o exception.o exportfs.o inferno.o kproc-pthreads.o latin1.o main.o parse.o pgrp.o print.o proc.o qio.o random.o segflush-386.o sysfile.o uqid.o emu.o ../../lib/libinterp.a ../../lib/libmath.a ../../lib/libdraw.a ../../lib/libmemlayer.a ../../lib/libmemdraw.a ../../lib/libkeyring.a ../../lib/libsec.a ../../lib/libmp.a ../../lib/lib9.a -lm -lX11 -lXext -lpthread
