9c -I../libmp des.c
9c -I../libmp desmodes.c
9c -I../libmp desECB.c
9c -I../libmp desCBC.c
9c -I../libmp des3ECB.c
9c -I../libmp des3CBC.c
9c -I../libmp aes.c
9c -I../libmp blowfish.c
9c -I../libmp idea.c
9c -I../libmp hmac.c
9c -I../libmp md5.c
9c -I../libmp md5block.c
9c -I../libmp md4.c
9c -I../libmp sha1.c
9c -I../libmp sha1block.c
9c -I../libmp sha1pickle.c
9c -I../libmp sha2.c
9c -I../libmp sha256block.c
9c -I../libmp sha512block.c
9c -I../libmp md5pickle.c
9c -I../libmp rc4.c
9c -I../libmp genrandom.c
9c -I../libmp prng.c
9c -I../libmp fastrand.c
9c -I../libmp nfastrand.c
9c -I../libmp probably_prime.c
9c -I../libmp smallprimetest.c
9c -I../libmp genprime.c
9c -I../libmp dsaprimes.c
9c -I../libmp gensafeprime.c
9c -I../libmp genstrongprime.c
9c -I../libmp rsagen.c
9c -I../libmp rsafill.c
9c -I../libmp rsaencrypt.c
9c -I../libmp rsadecrypt.c
9c -I../libmp rsaalloc.c
9c -I../libmp rsaprivtopub.c
9c -I../libmp eggen.c
9c -I../libmp egencrypt.c
9c -I../libmp egdecrypt.c
9c -I../libmp egalloc.c
9c -I../libmp egprivtopub.c
9c -I../libmp egsign.c
9c -I../libmp egverify.c
9c -I../libmp dsagen.c
9c -I../libmp dsaalloc.c
9c -I../libmp dsaprivtopub.c
9c -I../libmp dsasign.c
9c -I../libmp dsaverify.c
9ar  ../lib/libsec.a des.o desmodes.o desECB.o desCBC.o des3ECB.o des3CBC.o aes.o blowfish.o idea.o hmac.o md5.o md5block.o md4.o sha1.o sha1block.o sha1pickle.o sha2.o sha256block.o sha512block.o md5pickle.o rc4.o genrandom.o prng.o fastrand.o nfastrand.o probably_prime.o smallprimetest.o genprime.o dsaprimes.o gensafeprime.o genstrongprime.o rsagen.o rsafill.o rsaencrypt.o rsadecrypt.o rsaalloc.o rsaprivtopub.o eggen.o egencrypt.o egdecrypt.o egalloc.o egprivtopub.o egsign.o egverify.o dsagen.o dsaalloc.o dsaprivtopub.o dsasign.o dsaverify.o
