#!/dis/sh.dis
# stolen from p9p: /usr/local/plan9/bin/sig
load std

x=$*
*=`{echo $x | tr A-Z a-z | tr -dc 'a-z0-9_ \012'} # fold case, delete funny chars
if {no $*} {
	echo Usage: sig function ... >[1=2]
	exit 1
}

for i in $* {
	files=`{grep -il '[ 	]*'$i':[ 	]*fn\(' `{look $i /man/index | grep /man/2 | sed 's/^.*[ 	]//' | sort | uniq}}
	for j in $files {
		sect=`{basename $j}^'(2)'
		{echo .nr LL 20i; sed -n '/^.SH SYNOPSIS/,/^.SH.*DESCR/p'  $j} |
#			os nroff -man |
			sed '
				:a
				/,$|:$/ {
					N
					s/\n//
				}
				ta
				s/[ 	]+/ /g' |
			grep -i '[	]*'$i':[ 	]*fn\(' | sed 's/^[ ]+/	/; s/;$/; \# '$sect'/'
	}
}

exit 0
