9c  alloc.c
9c  allocimagemix.c
9c  arith.c
9c  bezier.c
9c  border.c
9c  buildfont.c
9c  bytesperline.c
9c  chan.c
9c  cloadimage.c
9c  computil.c
9c  creadimage.c
9c  defont.c
9c  draw.c
9c  drawrepl.c
9c  ellipse.c
9c  font.c
9c  freesubfont.c
9c  getdefont.c
9c  getsubfont.c
9c  init.c
9c  line.c
9c  mkfont.c
9c  openfont.c
9c  poly.c
9c  loadimage.c
9c  readimage.c
9c  readsubfont.c
9c  rectclip.c
9c  replclipr.c
9c  rgb.c
9c  string.c
9c  stringbg.c
9c  stringsubfont.c
9c  stringwidth.c
9c  subfont.c
9c  subfontcache.c
9c  subfontname.c
9c  unloadimage.c
9c  window.c
9c  writecolmap.c
9c  writeimage.c
9c  writesubfont.c
9ar  ../lib/libdraw.a alloc.o allocimagemix.o arith.o bezier.o border.o buildfont.o bytesperline.o chan.o cloadimage.o computil.o creadimage.o defont.o draw.o drawrepl.o ellipse.o font.o freesubfont.o getdefont.o getsubfont.o init.o line.o mkfont.o openfont.o poly.o loadimage.o readimage.o readsubfont.o rectclip.o replclipr.o rgb.o string.o stringbg.o stringsubfont.o stringwidth.o subfont.o subfontcache.o subfontname.o unloadimage.o window.o writecolmap.o writeimage.o writesubfont.o
