<$ROOT/mkconfig

LIB=libkeyring.a

OFILES=\
	dsaalg.$O\
	egalg.$O\
	rsaalg.$O

HFILES=\
	../include/mp.h\
	../include/libsec.h\
	../libinterp/runt.h\
	../include/interp.h\
	keys.h\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
