<../mkconfig

LIB=libmemdraw.a

COMMONFILES=\
	arc.$O\
	cmap.$O\
	cread.$O\
	defont.$O\
	ellipse.$O\
	fillpoly.$O\
	hwdraw.$O\
	icossin.$O\
	icossin2.$O\
	iprint.$O\
	line.$O\
	openmemsubfont.$O\
	poly.$O\
	read.$O\
	string.$O\
	subfont.$O\
	write.$O\
	
SYSFILES=alloc.$O\
	cload.$O\
	draw.$O\
	load.$O\
	unload.$O\

OFILES=$COMMONFILES $SYSFILES

HFILES=	../include/draw.h\
	../include/memdraw.h\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
