<$ROOT/mkconfig

DIRS=\
	lib\

TARG=\
	register.dis\
	reglisten.dis\
	regstyxlisten.dis\

MODULES=\

SYSMODULES=\
	arg.m\
	draw.m\
	grid/announce.m\
	keyring.m\
	registries.m\
	security.m\
	sh.m\
	sys.m\

DISBIN=$ROOT/dis/grid

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
