<$ROOT/mkconfig

TARG=adeb.dis

MODULES=adeb.m

SYSMODULES=\
	acmewin.m\
	arg.m\
	bufio.m\
	debug.m\
	dis.m\
	draw.m\
	plumbmsg.m\
	readdir.m\
	string.m\
	sys.m\
	workdir.m\

DISBIN=$ROOT/acme/dis
<$ROOT/mkfiles/mkdis

